version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ./env/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - app-network

  qval-app:
    build:
      context: ./src
      dockerfile: ./../Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    links:
      - postgres
      - redis
    env_file:
      - ./env/.env
    volumes:
      - .:/home/node/app
    networks:
      - app-network
    command: npm start

  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - qval-app
    networks:
      - app-network
    ports:
      - 80:80
      - 443:443
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis-data:
