version: '3.8'

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    secrets:
      - pg_db
      - pg_user
      - pg_password

  express:
    build: ./src
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - .env

