// Import action Queue from the bull module
const { actionQueue } = require('../bull');


/**
 * @module models/user.model
 * @name account.schema
 * @param {Object} sequelize - Sequelize object
 * @param {Object} Sequelize - Sequelize module
 * @returns {Object} - Returns object containing all the models
*/
module.exports = (sequelize, Sequelize, User, Topic, Reply, Story) => {
	/**
	 * @type {Model}
	 * @name User
	 * @description - This model contains all the user info
	 * @property {Number} id - Unique identifier for the user
	 * @property {String} name - Name of the user
	 * @property {String} username - Username of the user, usually an hash generated by the hash algorithms
	 * @property {String} email - Email of the user
	 * @property {String} password - Password of the user
	 * @property {Object} contact - Contact info of the user
	 * @property {String} bio - Bio of the user
	 * @property {String} picture - Profile picture of the user
	 * @property {Number} followers - Number of followers the user has
	 * @property {Number} following - Number of users the user is following
	 * @property {Number} stories - Number of stories the user has published.
	 * @property {Number} replies - Number of replies the user has published.
	 * @property {Number} views - Number of content views the user has.
	*/
	const Activity = sequelize.define("activities", {
		id: {
			type: Sequelize.INTEGER,
			primaryKey: true,
			autoIncrement: true,
		},
    kind: {
      type: Sequelize.ENUM('story', 'reply', 'topic', 'user'),
      allowNull: false,
      index: true,
    },
    action: {
      type: Sequelize.ENUM('follow', 'like', 'reply', 'create', 'update', 'vote', 'subscribe'),
      allowNull: false,
      index: true,
    },
		author: {
			type: Sequelize.STRING,
			allowNull: false,
      index: true,
		},
		hash: {
			type: Sequelize.STRING,
			unique: true,
			allowNull: true,
      index: true,
		},
		email: {
			type: Sequelize.STRING,
			unique: true,
			allowNull: false,
      index: true,
		},
		password: {
			type: Sequelize.STRING,
			allowNull: false
		},
		contact: {
			type: Sequelize.JSON,
			allowNull: true
		},
		bio: {
			type: Sequelize.TEXT,
			allowNull: true
		},
		picture: {
			type: Sequelize.STRING,
			allowNull: true
		},
		verified: {
			type: Sequelize.BOOLEAN,
			defaultValue: false,
			allowNull: true,
      index: true,
		},
		followers: {
			type: Sequelize.INTEGER,
			defaultValue: 0,
			allowNull: true,
      index: true,
		},
		following: {
			type: Sequelize.INTEGER,
			defaultValue: 0,
			allowNull: true,
      index: true,
		},
		stories: {
			type: Sequelize.INTEGER,
			defaultValue: 0,
			allowNull: true,
      index: true,
		},
		replies : {
			type: Sequelize.INTEGER,
			defaultValue: 0,
			allowNull: true,
      index: true,
		},
		views: {
			type: Sequelize.INTEGER,
			defaultValue: 0,
			allowNull: true,
      index: true,
		},
	},{
			schema: 'account',
			freezeTableName: true,
			timestamps: true,
      timezone: 'UTC',
			indexes: [
				{
					fields: ['createdAt']
				}
			]
	});

	// add afterSync hook to create the search column and create the GIN index
  User.afterSync(() => {
    // Run the raw SQL query to add the `ts` column
    sequelize.query(`
      ALTER TABLE account.users ADD COLUMN IF NOT EXISTS search tsvector
      GENERATED ALWAYS AS(setweight(to_tsvector('english', coalesce(name, '')), 'A')) STORED;
    `);

    // create the GIN index for the full_search column
    sequelize.query(`CREATE INDEX IF NOT EXISTS search_user_idx ON account.users USING GIN(search)`);
  });

	

	// add hook to connect model: afterCreate
	Connect.afterCreate(async connect => {
		// Add the connect to the queue
		await actionQueue.add('actionJob', {
			kind: 'user',
			hashes: {
				from: connect.from,
				to: connect.to
			},
			action: 'connect',
			value: 1
		}, { attempts: 3, backoff: 1000, removeOnComplete: true });
	});

	// add hook to connect model: afterDestroy
	Connect.afterDestroy(async connect => {
		// Add the connect to the queue
		await actionQueue.add('actionJob', {
			kind: 'user',
			hashes: {
				from: connect.from,
				to: connect.to
			},
			action: 'connect',
			value: -1
		}, { attempts: 3, backoff: 1000, removeOnComplete: true });
	});



	// Define associations for the Code and User model
	User.hasMany(Code, { foreignKey: 'email', sourceKey: 'email', onDelete: 'CASCADE' });
	Code.belongsTo(User, { foreignKey: 'email', targetKey: 'email', as: 'user_code', onDelete: 'CASCADE' });

	// Define associations for the Connect and User model
	User.hasMany(Connect, { foreignKey: 'from', sourceKey: 'hash', as: 'user_following', onDelete: 'CASCADE' });
	User.hasMany(Connect, { foreignKey: 'to', sourceKey: 'hash', as: 'user_followers', onDelete: 'CASCADE' });
	Connect.belongsTo(User, { foreignKey: 'from', targetKey: 'hash', as: 'from_user', onDelete: 'CASCADE' });
	Connect.belongsTo(User, { foreignKey: 'to', targetKey: 'hash', as: 'to_user', onDelete: 'CASCADE' });

	return {User, Code, Connect};
}