
/**
 * @module models/user.model
 * @name account.schema
 * @param {Object} sequelize - Sequelize object
 * @param {Object} Sequelize - Sequelize module
 * @returns {Object} - Returns object containing all the models
*/
module.exports = (sequelize, Sequelize) => {
	// noinspection JSUnresolvedFunction

	/**
	 * @type {Model}
	 * @name User
	 * @description - This model contains all the user info
	 * @property {Number} id - Unique identifier for the user
	 * @property {String} name - Name of the user
	 * @property {String} username - Username of the user, usually an hash generated by the hash algorithms
	 * @property {String} email - Email of the user
	 * @property {String} password - Password of the user
	 * @property {Object} contact - Contact info of the user
	 * @property {String} bio - Bio of the user
	 * @property {String} picture - Profile picture of the user
	*/
	const User = sequelize.define("users", {
		id: {
			type: Sequelize.INTEGER,
			primaryKey: true,
			autoIncrement: true,
		},
		name: {
			type: Sequelize.STRING,
			allowNull: false
		},
		username: {
			type: Sequelize.STRING,
			unique: true,
			allowNull: true
		},
		email: {
			type: Sequelize.STRING,
			unique: true,
			allowNull: false
		},
		password: {
			type: Sequelize.STRING,
			allowNull: false
		},
		contact: {
			type: Sequelize.JSON,
			allowNull: true
		},
		bio: {
			type: Sequelize.TEXT,
			allowNull: true
		},
		picture: {
			type: Sequelize.STRING,
			allowNull: true
		}
	},{
			schema: 'account',
			freezeTableName: true,
			indexes: [
				{
					unique: true,
					fields: ['id', 'username']
				},
				{
					fields: ['email']
				}
			]
	});

	return {User};
}