
/**
 * @module models/user.model
 * @name account.schema
 * @param {Object} sequelize - Sequelize object
 * @param {Object} Sequelize - Sequelize module
 * @returns {Object} - Returns object containing all the models
*/
module.exports = (sequelize, Sequelize) => {
	/**
	 * @type {Model}
	 * @name User
	 * @description - This model contains all the user info
	 * @property {Number} id - Unique identifier for the user
	 * @property {String} name - Name of the user
	 * @property {String} username - Username of the user, usually an hash generated by the hash algorithms
	 * @property {String} email - Email of the user
	 * @property {String} password - Password of the user
	 * @property {Object} contact - Contact info of the user
	 * @property {String} bio - Bio of the user
	 * @property {String} picture - Profile picture of the user
	 * @property {Number} followers - Number of followers the user has
	 * @property {Number} following - Number of users the user is following
	 * @property {Number} stories - Number of stories the user has published.
	*/
	const User = sequelize.define("users", {
		id: {
			type: Sequelize.INTEGER,
			primaryKey: true,
			autoIncrement: true,
		},
		name: {
			type: Sequelize.STRING,
			allowNull: false
		},
		hash: {
			type: Sequelize.STRING,
			unique: true,
			allowNull: true
		},
		email: {
			type: Sequelize.STRING,
			unique: true,
			allowNull: false
		},
		password: {
			type: Sequelize.STRING,
			allowNull: false
		},
		contact: {
			type: Sequelize.JSON,
			allowNull: true
		},
		bio: {
			type: Sequelize.TEXT,
			allowNull: true
		},
		picture: {
			type: Sequelize.STRING,
			allowNull: true
		},
		followers: {
			type: Sequelize.INTEGER,
			defaultValue: 0,
			allowNull: true,
		},
		following: {
			type: Sequelize.INTEGER,
			defaultValue: 0,
			allowNull: true,
		},
		stories: {
			type: Sequelize.INTEGER,
			defaultValue: 0,
			allowNull: true,
		},
	},{
			schema: 'account',
			freezeTableName: true,
			indexes: [
				{
					unique: true,
					fields: ['id', 'hash', 'email']
				}
			]
	});


	/**
	 * @type {Model}
	 * @name Code
	 * @description - This model contains all reset password codes
	 * @property {Number} id - Unique identifier for the code
	 * @property {String} code - The reset password code
	 * @property {String} email - Email of the user
	 * @property {Date} expires - Expiry date of the code
	*/
	const Code = sequelize.define("codes", {
		id: {
			type: Sequelize.INTEGER,
			primaryKey: true,
			autoIncrement: true,
		},
		code: {
			type: Sequelize.STRING,
			allowNull: false
		},
		email: {
			type: Sequelize.STRING,
			allowNull: false
		},
		expires: {
			type: Sequelize.DATE,
			allowNull: false
		}
	},{
		schema: 'account',
		freezeTableName: true,
		indexes: [
			{
				unique: true,
				fields: ['id', 'code', 'email']
			}
		]
	});


	/**
	 * @type {Model}
	 * @name Connect
	 * @description - This model contains all the user connections
	 * @property {Number} id - Unique identifier for the connection
	 * @property {String} from - The hash of the user who initiated the connection
	 * @property {String} to - The hash of the user who received the connection
	 * @property {Boolean} active - The status of the connection
	 * @property {Date} deleatedAt - The date the connection was deleted
	*/
	const Connect = sequelize.define("connects", {
		id: {
			type: Sequelize.INTEGER,
			primaryKey: true,
			autoIncrement: true,
		},
		from: {
			type: Sequelize.STRING,
			allowNull: false
		},
		to: {
			type: Sequelize.STRING,
			allowNull: false
		},
		active: {
			type: Sequelize.BOOLEAN,
			defaultValue: false,
			allowNull: false
		},
		deleatedAt: {
			type: Sequelize.DATE,
			allowNull: true
		}
	},{
		schema: 'account',
		freezeTableName: true,
		indexes: [
			{
				unique: true,
				fields: ['id', 'from', 'to']
			}
		]
	});

	// Define associations for the Code and User model
	User.hasMany(Code, { foreignKey: 'email', sourceKey: 'email', onDelete: 'CASCADE' });
	Code.belongsTo(User, { foreignKey: 'email', targetKey: 'email', as: 'user_code', onDelete: 'CASCADE' });

	// Define associations for the Connect and User model
	User.hasMany(Connect, { foreignKey: 'from', sourceKey: 'hash', onDelete: 'CASCADE' });
	User.hasMany(Connect, { foreignKey: 'to', sourceKey: 'hash', onDelete: 'CASCADE' });
	Connect.belongsTo(User, { foreignKey: 'from', targetKey: 'hash', as: 'from_user', onDelete: 'CASCADE' });
	Connect.belongsTo(User, { foreignKey: 'to', targetKey: 'hash', as: 'to_user', onDelete: 'CASCADE' });

	return {User, Code, Connect};
}